### ISSUE TITLE
["BUG"] Validation error in Get request (nutmeg version)

### ISSUE THREAD

**Issue by felipemontoya** [eduNEXT/eox-core#241]
**Describe the bug**

We have a validation error in:

File /openedx/venv/lib/python3.8/site-packages/eox_core/api/v1/views.py, line 776, in get

This used to work well, since the nutmeg migration, we are seeing that the Validation Error gets trapped in a loop of excepts.

Thiis is the stack trace:

```
Error message
[ErrorDetail(string='You have to provide a course_id', code='invalid')]

Traceback (most recent call last):
File "/openedx/venv/lib/python3.8/site-packages/newrelic/api/function_trace.py", line 166, in literal_wrapper
File "/openedx/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 50, in inner
File "/openedx/venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 120, in __call__
File "/openedx/venv/lib/python3.8/site-packages/newrelic/hooks/framework_django.py", line 1195, in _wrapper
File "/openedx/venv/lib/python3.8/site-packages/newrelic/api/function_trace.py", line 166, in literal_wrapper
File "/openedx/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 50, in inner
File "/openedx/venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 120, in __call__
File "/openedx/venv/lib/python3.8/site-packages/newrelic/hooks/framework_django.py", line 1195, in _wrapper
File "/openedx/venv/lib/python3.8/site-packages/newrelic/api/function_trace.py", line 166, in literal_wrapper
File "/openedx/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 50, in inner
File "/openedx/venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 120, in __call__
File "/openedx/venv/lib/python3.8/site-packages/newrelic/hooks/framework_django.py", line 1195, in _wrapper
File "/openedx/venv/lib/python3.8/site-packages/newrelic/api/function_trace.py", line 166, in literal_wrapper
File "/openedx/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 50, in inner
File "/openedx/requirements/eox-support/eox_support/middleware.py", line 20, in __call__
File "/openedx/venv/lib/python3.8/site-packages/newrelic/hooks/framework_django.py", line 1195, in _wrapper
File "/openedx/venv/lib/python3.8/site-packages/newrelic/api/function_trace.py", line 166, in literal_wrapper
File "/openedx/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 50, in inner
File "/openedx/venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 120, in __call__
File "/openedx/venv/lib/python3.8/site-packages/newrelic/hooks/framework_django.py", line 1195, in _wrapper
File "/openedx/venv/lib/python3.8/site-packages/newrelic/api/function_trace.py", line 166, in literal_wrapper
File "/openedx/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 50, in inner
File "/openedx/venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 120, in __call__
File "/openedx/venv/lib/python3.8/site-packages/newrelic/hooks/framework_django.py", line 1195, in _wrapper
File "/openedx/venv/lib/python3.8/site-packages/newrelic/api/function_trace.py", line 166, in literal_wrapper
File "/openedx/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 50, in inner
File "/openedx/venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 120, in __call__
File "/openedx/venv/lib/python3.8/site-packages/newrelic/hooks/framework_django.py", line 1195, in _wrapper
File "/openedx/venv/lib/python3.8/site-packages/newrelic/api/function_trace.py", line 166, in literal_wrapper
File "/openedx/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 50, in inner
File "/openedx/venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 120, in __call__
File "/openedx/venv/lib/python3.8/site-packages/newrelic/hooks/framework_django.py", line 1195, in _wrapper
File "/openedx/venv/lib/python3.8/site-packages/newrelic/api/function_trace.py", line 166, in literal_wrapper
File "/openedx/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 50, in inner
File "/openedx/venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 120, in __call__
File "/openedx/venv/lib/python3.8/site-packages/newrelic/hooks/framework_django.py", line 1195, in _wrapper
File "/openedx/venv/lib/python3.8/site-packages/newrelic/api/function_trace.py", line 166, in literal_wrapper
File "/openedx/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 50, in inner
File "/openedx/venv/lib/python3.8/site-packages/django/utils/deprecation.py", line 120, in __call__
File "/openedx/venv/lib/python3.8/site-packages/newrelic/hooks/framework_django.py", line 1195, in _wrapper
File "/openedx/venv/lib/python3.8/site-packages/newrelic/api/function_trace.py", line 166, in literal_wrapper
File "/openedx/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 50, in inner
File "/openedx/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 210, in _get_response
File "/opt/pyenv/versions/3.8.12/lib/python3.8/contextlib.py", line 75, in inner
File "/openedx/venv/lib/python3.8/site-packages/newrelic/hooks/framework_django.py", line 552, in wrapper
File "/openedx/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
File "/openedx/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
File "/openedx/venv/lib/python3.8/site-packages/newrelic/hooks/component_djangorestframework.py", line 61, in _nr_wrapper_APIView_dispatch_
File "/openedx/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
File "/openedx/venv/lib/python3.8/site-packages/eox_core/api/v1/views.py", line 776, in get
```

**Expected behavior**
The error should reach the consumer.

**Additional context**
https://one.newrelic.com/nr1-core/errors/overview/MzM1MjM0fEFQTXxBUFBMSUNBVElPTnw5ODQ0OTkyMzk?account=335234&duration=1800000&filters=%28domain%20IN%20%28%27APM%27%2C%20%27EXT%27%29%20AND%20type%20IN%20%28%27APPLICATION%27%2C%20%27SERVICE%27%29%29&state=9ac84b34-68a1-4c65-87d2-6512b45b474c

**Comment by JuanDavidBuitrago** [comment]
This is not a bug, we found one of ours customers made some internal upgrading that are not working as expected. Here the [Basecapms](https://3.basecamp.com/3966315/buckets/22136261/todos/5728625009) conversation.
